# -*- coding: utf-8 -*-

from ..paths import dir_asset

class CategoryIconEnum:
    arch_category_compute = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Compute_64.png")
    arch_category_analytics = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Analytics_64.png")
    arch_category_customer_enablement = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Customer-Enablement_64.png")
    arch_category_machine_learning = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Machine-Learning_64.png")
    arch_category_serverless = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Serverless_64.png")
    arch_category_front_end_web_mobile = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Front-End-Web-Mobile_64.png")
    arch_category_containers = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Containers_64.png")
    arch_category_storage = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Storage_64.png")
    arch_category_security_identity_compliance = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Security-Identity-Compliance_64.png")
    arch_category_robotics = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Robotics_64.png")
    arch_category_contact_center = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Contact-Center_64.png")
    arch_category_media_services = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Media-Services_64.png")
    arch_category_quantum_technologies = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Quantum-Technologies_64.png")
    arch_category_database = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Database_64.png")
    arch_category_management_governance = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Management-Governance_64.png")
    arch_category_developer_tools = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Developer-Tools_64.png")
    arch_category_migration_transfer = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Migration-Transfer_64.png")
    arch_category_cloud_financial_management = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Cloud-Financial-Management_64.png")
    arch_category_application_integration = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Application-Integration_64.png")
    arch_category_satellite = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Satellite_64.png")
    arch_category_games = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Games_64.png")
    arch_category_end_user_computing = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_End-User-Computing_64.png")
    arch_category_business_applications = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Business-Applications_64.png")
    arch_category_internet_of_things = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Internet-of-Things_64.png")
    arch_category_blockchain = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Blockchain_64.png")
    arch_category_networking_content_delivery = dir_asset.joinpath("Category-Icons_10232023/Arch-Category_64/Arch-Category_Networking-Content-Delivery_64.png")
